### ISSUE TITLE
[CaffeineMessages] FAILED KEEPALIVE

### ISSUE THREAD

**Issue by e3ndr** [Casterlabs/Koi#2]
```
[SEVERE] [WebUtil] Invalid json: 
FAILED KEEPALIVE
[SEVERE] [CaffeineMessages] java.lang.Exception: FAILED KEEPALIVE
	at co.casterlabs.koi.util.WebUtil.getJsonFromString(WebUtil.java:33)
	at co.casterlabs.koi.user.caffeine.CaffeineMessages.onMessage(CaffeineMessages.java:64)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:591)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:508)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at co.casterlabs.koi.util.WebUtil.getJsonFromString(WebUtil.java:29)
	... 8 more
```

**Comment by e3ndr** [comment]
Fixed in [#4dd40c9](https://github.com/Casterlabs/Koi/commit/c7e1b2f26e0cccc1c0132adab38f0c50075f40b5)
