### ISSUE TITLE
[CaffeineQuery] com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject

### ISSUE THREAD

**Issue by e3ndr** [Casterlabs/Koi#3]
```
[SEVERE] [CaffeineQuery] java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject
	at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:192)
	at co.casterlabs.koi.user.caffeine.CaffeineQuery.onMessage(CaffeineQuery.java:53)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:591)
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:885)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:819)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:379)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:216)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:508)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by e3ndr** [comment]
Added verbosity in [#7eb316a](https://github.com/Casterlabs/Koi/commit/ff691a6762a12be993b010d075d2408c9017a7a7)  in order to attempt to debug the problem.

**Comment by e3ndr** [comment]
Additional information (payload):
`{"payload":{"errors":[{"message":"credential expired","path":["stage"]}],"data":null},"id":"1","type":"data"}`

**Comment by e3ndr** [comment]
Seems to have been fixed in an earlier commit, closing for now.
